### ISSUE TITLE
Suggestion: Configurable Stash Options

### ISSUE THREAD

**Issue by bandgeekndb** [jimathy/jim_bridge#1]
Hello! I'm upgrading jim-mechanic to v3.3 and one thing I noticed was that the openStash function in jim_bridge didn't support customizing the stash options.

I made the following change to allow passing through a stashOptions variable:

```lua
function openStash(data)
    if (data.job or data.gang) and not jobCheck(data.job or data.gang) then return end
    if GetResourceState(OXInv):find("start") then
        exports[OXInv]:openInventory('stash', data.stash)
    elseif GetResourceState(CodeMInv):find("start") then
        exports[CodeMInv]:OpenStash(data.stash, 400000, 100)
    else
        TriggerEvent("inventory:client:SetCurrentStash", data.stash)
        TriggerServerEvent("inventory:server:OpenInventory", "stash", data.stash, data.stashOptions)
    end
    lookEnt(data.coords)
end
```

This way, when calling openStash from jim-mechanic, I can do this:

```lua
{ action = function()
	openStash({ job = loc.job, stash = repairStashName, stashOptions = { maxweight = 4000000, slots = 200, } }) end,
	icon = "fas fa-cogs",
	label = Loc[Config.Lan]["repair"].browse,
	job = loc.job
},
```

I know jim_bridge is still pretty new and if you're not looking for any feedback like this, go ahead and close this, no worries. I just wanted to share in case others are interested in doing the same thing and maybe it helps you in the future if you ever need to customize a stash.

**Comment by McKlean** [comment]
We are defo looking for adjustments thats why this was put on github instead of tebex. please feel free to do a Pull Request to add it in

**Comment by bandgeekndb** [comment]
Perfect, #3 opened to add this change
